name:                wifi
version:             0.0.0.0
license:             MIT

dependencies:
- base < 5

library:
  source-dirs: src
  dependencies:
  - brick
  - cursor
  - cursor-brick
  - directory
  - path
  - path-io
  - pretty-show
  - text
  - vty
  - process
  - parsec

executables:
  wifi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wifi
